# Generated by Django 5.2.8 on 2025-11-10 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('CLP', 'Peso chileno'), ('COP', 'Peso colombiano'), ('PEN', 'Sol peruano'), ('USD', 'Dólar estadounidense')], max_length=3, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('CLP', 'Peso chileno'), ('COP', 'Peso colombiano'), ('PEN', 'Sol peruano'), ('USD', 'Dólar estadounidense')], max_length=3)),
                ('location', models.CharField(choices=[('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Perú'), ('US', 'Estados Unidos')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
